[package]
name = "blake-udf"
version = "0.1.0"
edition = "2021"

[lib]
name = "blake_udf"
crate-type = ["cdylib"]


[dependencies]
libc = "0.2"
blake3 = "1.3.1"

[build-dependencies]
cbindgen = "0.20.0"
bindgen = "0.53.1"
